/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.enums;


import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum OrderOrderStatus implements EnumType {

    NEW("NEW"),

    PROCESSING("PROCESSING"),

    COMPLETED("COMPLETED"),

    SHIPPING_METHOD_PENDING("SHIPPING_METHOD_PENDING"),

    S2K_SUBMIT_PENDING("S2K_SUBMIT_PENDING"),

    S2K_SUBMIT_FAILED("S2K_SUBMIT_FAILED");

    private final String literal;

    private OrderOrderStatus(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return null;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "order_order_status";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
