/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.enums.CartShippingPromotionType;
import com.scratch.database.mysql.jv.tables.Cart;
import com.scratch.database.mysql.jv.tables.records.CartRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CartDao extends DAOImpl<CartRecord, com.scratch.database.mysql.jv.tables.pojos.Cart, ULong> {

    /**
     * Create a new CartDao without any configuration
     */
    public CartDao() {
        super(Cart.CART, com.scratch.database.mysql.jv.tables.pojos.Cart.class);
    }

    /**
     * Create a new CartDao with an attached configuration
     */
    public CartDao(Configuration configuration) {
        super(Cart.CART, com.scratch.database.mysql.jv.tables.pojos.Cart.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.Cart object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchById(ULong... values) {
        return fetch(Cart.CART.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.Cart fetchOneById(ULong value) {
        return fetchOne(Cart.CART.ID, value);
    }

    /**
     * Fetch records that have <code>session_id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchBySessionId(String... values) {
        return fetch(Cart.CART.SESSION_ID, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByUserId(ULong... values) {
        return fetch(Cart.CART.USER_ID, values);
    }

    /**
     * Fetch records that have <code>item_number IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByItemNumber(String... values) {
        return fetch(Cart.CART.ITEM_NUMBER, values);
    }

    /**
     * Fetch records that have <code>price IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByPrice(BigDecimal... values) {
        return fetch(Cart.CART.PRICE, values);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByQuantity(BigDecimal... values) {
        return fetch(Cart.CART.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>discount_percent IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByDiscountPercent(UInteger... values) {
        return fetch(Cart.CART.DISCOUNT_PERCENT, values);
    }

    /**
     * Fetch records that have <code>discount_price IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByDiscountPrice(BigDecimal... values) {
        return fetch(Cart.CART.DISCOUNT_PRICE, values);
    }

    /**
     * Fetch records that have <code>promo_code IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByPromoCode(String... values) {
        return fetch(Cart.CART.PROMO_CODE, values);
    }

    /**
     * Fetch records that have <code>shipping_promotion_type IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByShippingPromotionType(CartShippingPromotionType... values) {
        return fetch(Cart.CART.SHIPPING_PROMOTION_TYPE, values);
    }

    /**
     * Fetch records that have <code>shipping_promotion_amount IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByShippingPromotionAmount(BigDecimal... values) {
        return fetch(Cart.CART.SHIPPING_PROMOTION_AMOUNT, values);
    }

    /**
     * Fetch records that have <code>shipping_promotion_method IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByShippingPromotionMethod(String... values) {
        return fetch(Cart.CART.SHIPPING_PROMOTION_METHOD, values);
    }

    /**
     * Fetch records that have <code>updated_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByUpdatedTs(Timestamp... values) {
        return fetch(Cart.CART.UPDATED_TS, values);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Cart> fetchByCreatedTs(Timestamp... values) {
        return fetch(Cart.CART.CREATED_TS, values);
    }
}
