/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.tables.Ingredient;
import com.scratch.database.mysql.jv.tables.records.IngredientRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IngredientDao extends DAOImpl<IngredientRecord, com.scratch.database.mysql.jv.tables.pojos.Ingredient, ULong> {

    /**
     * Create a new IngredientDao without any configuration
     */
    public IngredientDao() {
        super(Ingredient.INGREDIENT, com.scratch.database.mysql.jv.tables.pojos.Ingredient.class);
    }

    /**
     * Create a new IngredientDao with an attached configuration
     */
    public IngredientDao(Configuration configuration) {
        super(Ingredient.INGREDIENT, com.scratch.database.mysql.jv.tables.pojos.Ingredient.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.Ingredient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Ingredient> fetchById(ULong... values) {
        return fetch(Ingredient.INGREDIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.Ingredient fetchOneById(ULong value) {
        return fetchOne(Ingredient.INGREDIENT.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Ingredient> fetchByName(String... values) {
        return fetch(Ingredient.INGREDIENT.NAME, values);
    }

    /**
     * Fetch records that have <code>updated_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Ingredient> fetchByUpdatedTs(Timestamp... values) {
        return fetch(Ingredient.INGREDIENT.UPDATED_TS, values);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Ingredient> fetchByCreatedTs(Timestamp... values) {
        return fetch(Ingredient.INGREDIENT.CREATED_TS, values);
    }
}
