/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.enums.LogLevel;
import com.scratch.database.mysql.jv.tables.Log;
import com.scratch.database.mysql.jv.tables.records.LogRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LogDao extends DAOImpl<LogRecord, com.scratch.database.mysql.jv.tables.pojos.Log, ULong> {

    /**
     * Create a new LogDao without any configuration
     */
    public LogDao() {
        super(Log.LOG, com.scratch.database.mysql.jv.tables.pojos.Log.class);
    }

    /**
     * Create a new LogDao with an attached configuration
     */
    public LogDao(Configuration configuration) {
        super(Log.LOG, com.scratch.database.mysql.jv.tables.pojos.Log.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.Log object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchById(ULong... values) {
        return fetch(Log.LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.Log fetchOneById(ULong value) {
        return fetchOne(Log.LOG.ID, value);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchByCreatedTs(Timestamp... values) {
        return fetch(Log.LOG.CREATED_TS, values);
    }

    /**
     * Fetch records that have <code>level IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchByLevel(LogLevel... values) {
        return fetch(Log.LOG.LEVEL, values);
    }

    /**
     * Fetch records that have <code>event IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchByEvent(String... values) {
        return fetch(Log.LOG.EVENT, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchByDescription(String... values) {
        return fetch(Log.LOG.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>before IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchByBefore(String... values) {
        return fetch(Log.LOG.BEFORE, values);
    }

    /**
     * Fetch records that have <code>after IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.Log> fetchByAfter(String... values) {
        return fetch(Log.LOG.AFTER, values);
    }
}
