/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.tables.OrderTrackingInfo;
import com.scratch.database.mysql.jv.tables.records.OrderTrackingInfoRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderTrackingInfoDao extends DAOImpl<OrderTrackingInfoRecord, com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo, ULong> {

    /**
     * Create a new OrderTrackingInfoDao without any configuration
     */
    public OrderTrackingInfoDao() {
        super(OrderTrackingInfo.ORDER_TRACKING_INFO, com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo.class);
    }

    /**
     * Create a new OrderTrackingInfoDao with an attached configuration
     */
    public OrderTrackingInfoDao(Configuration configuration) {
        super(OrderTrackingInfo.ORDER_TRACKING_INFO, com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo> fetchById(ULong... values) {
        return fetch(OrderTrackingInfo.ORDER_TRACKING_INFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo fetchOneById(ULong value) {
        return fetchOne(OrderTrackingInfo.ORDER_TRACKING_INFO.ID, value);
    }

    /**
     * Fetch records that have <code>order_id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo> fetchByOrderId(ULong... values) {
        return fetch(OrderTrackingInfo.ORDER_TRACKING_INFO.ORDER_ID, values);
    }

    /**
     * Fetch records that have <code>tracking_number IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo> fetchByTrackingNumber(String... values) {
        return fetch(OrderTrackingInfo.ORDER_TRACKING_INFO.TRACKING_NUMBER, values);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo> fetchByCreatedTs(Timestamp... values) {
        return fetch(OrderTrackingInfo.ORDER_TRACKING_INFO.CREATED_TS, values);
    }

    /**
     * Fetch records that have <code>updated_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.OrderTrackingInfo> fetchByUpdatedTs(Timestamp... values) {
        return fetch(OrderTrackingInfo.ORDER_TRACKING_INFO.UPDATED_TS, values);
    }
}
