/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.enums.RecipeIngredientType;
import com.scratch.database.mysql.jv.tables.RecipeIngredient;
import com.scratch.database.mysql.jv.tables.records.RecipeIngredientRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeIngredientDao extends DAOImpl<RecipeIngredientRecord, com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient, ULong> {

    /**
     * Create a new RecipeIngredientDao without any configuration
     */
    public RecipeIngredientDao() {
        super(RecipeIngredient.RECIPE_INGREDIENT, com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient.class);
    }

    /**
     * Create a new RecipeIngredientDao with an attached configuration
     */
    public RecipeIngredientDao(Configuration configuration) {
        super(RecipeIngredient.RECIPE_INGREDIENT, com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchById(ULong... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient fetchOneById(ULong value) {
        return fetchOne(RecipeIngredient.RECIPE_INGREDIENT.ID, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByType(RecipeIngredientType... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.TYPE, values);
    }

    /**
     * Fetch records that have <code>related_id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByRelatedId(String... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.RELATED_ID, values);
    }

    /**
     * Fetch records that have <code>recipe_ingredient_group_id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByRecipeIngredientGroupId(ULong... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.RECIPE_INGREDIENT_GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>amount IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByAmount(String... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.AMOUNT, values);
    }

    /**
     * Fetch records that have <code>uom IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByUom(String... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.UOM, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByDescription(String... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>updated_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByUpdatedTs(Timestamp... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.UPDATED_TS, values);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.RecipeIngredient> fetchByCreatedTs(Timestamp... values) {
        return fetch(RecipeIngredient.RECIPE_INGREDIENT.CREATED_TS, values);
    }
}
