/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.tables.SearchKeyword;
import com.scratch.database.mysql.jv.tables.records.SearchKeywordRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SearchKeywordDao extends DAOImpl<SearchKeywordRecord, com.scratch.database.mysql.jv.tables.pojos.SearchKeyword, ULong> {

    /**
     * Create a new SearchKeywordDao without any configuration
     */
    public SearchKeywordDao() {
        super(SearchKeyword.SEARCH_KEYWORD, com.scratch.database.mysql.jv.tables.pojos.SearchKeyword.class);
    }

    /**
     * Create a new SearchKeywordDao with an attached configuration
     */
    public SearchKeywordDao(Configuration configuration) {
        super(SearchKeyword.SEARCH_KEYWORD, com.scratch.database.mysql.jv.tables.pojos.SearchKeyword.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.SearchKeyword object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.SearchKeyword> fetchById(ULong... values) {
        return fetch(SearchKeyword.SEARCH_KEYWORD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.SearchKeyword fetchOneById(ULong value) {
        return fetchOne(SearchKeyword.SEARCH_KEYWORD.ID, value);
    }

    /**
     * Fetch records that have <code>search_keyword IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.SearchKeyword> fetchBySearchKeyword(String... values) {
        return fetch(SearchKeyword.SEARCH_KEYWORD.SEARCH_KEYWORD_, values);
    }

    /**
     * Fetch records that have <code>replacement_keyword IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.SearchKeyword> fetchByReplacementKeyword(String... values) {
        return fetch(SearchKeyword.SEARCH_KEYWORD.REPLACEMENT_KEYWORD, values);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.SearchKeyword> fetchByCreatedTs(Timestamp... values) {
        return fetch(SearchKeyword.SEARCH_KEYWORD.CREATED_TS, values);
    }

    /**
     * Fetch records that have <code>updated_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.SearchKeyword> fetchByUpdatedTs(Timestamp... values) {
        return fetch(SearchKeyword.SEARCH_KEYWORD.UPDATED_TS, values);
    }
}
