/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.daos;


import com.scratch.database.mysql.jv.enums.TagGroupConstants;
import com.scratch.database.mysql.jv.tables.TagGroup;
import com.scratch.database.mysql.jv.tables.records.TagGroupRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagGroupDao extends DAOImpl<TagGroupRecord, com.scratch.database.mysql.jv.tables.pojos.TagGroup, ULong> {

    /**
     * Create a new TagGroupDao without any configuration
     */
    public TagGroupDao() {
        super(TagGroup.TAG_GROUP, com.scratch.database.mysql.jv.tables.pojos.TagGroup.class);
    }

    /**
     * Create a new TagGroupDao with an attached configuration
     */
    public TagGroupDao(Configuration configuration) {
        super(TagGroup.TAG_GROUP, com.scratch.database.mysql.jv.tables.pojos.TagGroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ULong getId(com.scratch.database.mysql.jv.tables.pojos.TagGroup object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchById(ULong... values) {
        return fetch(TagGroup.TAG_GROUP.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.scratch.database.mysql.jv.tables.pojos.TagGroup fetchOneById(ULong value) {
        return fetchOne(TagGroup.TAG_GROUP.ID, value);
    }

    /**
     * Fetch records that have <code>section IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchBySection(String... values) {
        return fetch(TagGroup.TAG_GROUP.SECTION, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchByName(String... values) {
        return fetch(TagGroup.TAG_GROUP.NAME, values);
    }

    /**
     * Fetch records that have <code>is_filter IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchByIsFilter(Byte... values) {
        return fetch(TagGroup.TAG_GROUP.IS_FILTER, values);
    }

    /**
     * Fetch records that have <code>isRelatable IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchByIsrelatable(Byte... values) {
        return fetch(TagGroup.TAG_GROUP.ISRELATABLE, values);
    }

    /**
     * Fetch records that have <code>updated_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchByUpdatedTs(Timestamp... values) {
        return fetch(TagGroup.TAG_GROUP.UPDATED_TS, values);
    }

    /**
     * Fetch records that have <code>created_ts IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchByCreatedTs(Timestamp... values) {
        return fetch(TagGroup.TAG_GROUP.CREATED_TS, values);
    }

    /**
     * Fetch records that have <code>constants IN (values)</code>
     */
    public List<com.scratch.database.mysql.jv.tables.pojos.TagGroup> fetchByConstants(TagGroupConstants... values) {
        return fetch(TagGroup.TAG_GROUP.CONSTANTS, values);
    }
}
