/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountFilter implements Serializable {

    private static final long serialVersionUID = 81175436;

    private final ULong id;
    private final ULong accountId;
    private final ULong tagId;

    public AccountFilter(AccountFilter value) {
        this.id = value.id;
        this.accountId = value.accountId;
        this.tagId = value.tagId;
    }

    public AccountFilter(
        ULong id,
        ULong accountId,
        ULong tagId
    ) {
        this.id = id;
        this.accountId = accountId;
        this.tagId = tagId;
    }

    public ULong getId() {
        return this.id;
    }

    public ULong getAccountId() {
        return this.accountId;
    }

    public ULong getTagId() {
        return this.tagId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountFilter (");

        sb.append(id);
        sb.append(", ").append(accountId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
