/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import com.scratch.database.mysql.jv.enums.CommentStatus;
import com.scratch.database.mysql.jv.enums.CommentType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Comment implements Serializable {

    private static final long serialVersionUID = 746411353;

    private ULong         id;
    private CommentType   type;
    private String        relatedId;
    private Long          accountId;
    private String        name;
    private String        comment;
    private CommentStatus status;
    private String        approvalUser;
    private Byte          isDeleted;
    private Timestamp     updatedTs;
    private Timestamp     createdTs;

    public Comment() {}

    public Comment(Comment value) {
        this.id = value.id;
        this.type = value.type;
        this.relatedId = value.relatedId;
        this.accountId = value.accountId;
        this.name = value.name;
        this.comment = value.comment;
        this.status = value.status;
        this.approvalUser = value.approvalUser;
        this.isDeleted = value.isDeleted;
        this.updatedTs = value.updatedTs;
        this.createdTs = value.createdTs;
    }

    public Comment(
        ULong         id,
        CommentType   type,
        String        relatedId,
        Long          accountId,
        String        name,
        String        comment,
        CommentStatus status,
        String        approvalUser,
        Byte          isDeleted,
        Timestamp     updatedTs,
        Timestamp     createdTs
    ) {
        this.id = id;
        this.type = type;
        this.relatedId = relatedId;
        this.accountId = accountId;
        this.name = name;
        this.comment = comment;
        this.status = status;
        this.approvalUser = approvalUser;
        this.isDeleted = isDeleted;
        this.updatedTs = updatedTs;
        this.createdTs = createdTs;
    }

    public ULong getId() {
        return this.id;
    }

    public Comment setId(ULong id) {
        this.id = id;
        return this;
    }

    public CommentType getType() {
        return this.type;
    }

    public Comment setType(CommentType type) {
        this.type = type;
        return this;
    }

    public String getRelatedId() {
        return this.relatedId;
    }

    public Comment setRelatedId(String relatedId) {
        this.relatedId = relatedId;
        return this;
    }

    public Long getAccountId() {
        return this.accountId;
    }

    public Comment setAccountId(Long accountId) {
        this.accountId = accountId;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Comment setName(String name) {
        this.name = name;
        return this;
    }

    public String getComment() {
        return this.comment;
    }

    public Comment setComment(String comment) {
        this.comment = comment;
        return this;
    }

    public CommentStatus getStatus() {
        return this.status;
    }

    public Comment setStatus(CommentStatus status) {
        this.status = status;
        return this;
    }

    public String getApprovalUser() {
        return this.approvalUser;
    }

    public Comment setApprovalUser(String approvalUser) {
        this.approvalUser = approvalUser;
        return this;
    }

    public Byte getIsDeleted() {
        return this.isDeleted;
    }

    public Comment setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }

    public Timestamp getUpdatedTs() {
        return this.updatedTs;
    }

    public Comment setUpdatedTs(Timestamp updatedTs) {
        this.updatedTs = updatedTs;
        return this;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public Comment setCreatedTs(Timestamp createdTs) {
        this.createdTs = createdTs;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Comment (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(relatedId);
        sb.append(", ").append(accountId);
        sb.append(", ").append(name);
        sb.append(", ").append(comment);
        sb.append(", ").append(status);
        sb.append(", ").append(approvalUser);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(updatedTs);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
