/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import com.scratch.database.mysql.jv.enums.LogLevel;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Log implements Serializable {

    private static final long serialVersionUID = 1223205384;

    private final ULong     id;
    private final Timestamp createdTs;
    private final LogLevel  level;
    private final String    event;
    private final String    description;
    private final String    before;
    private final String    after;

    public Log(Log value) {
        this.id = value.id;
        this.createdTs = value.createdTs;
        this.level = value.level;
        this.event = value.event;
        this.description = value.description;
        this.before = value.before;
        this.after = value.after;
    }

    public Log(
        ULong     id,
        Timestamp createdTs,
        LogLevel  level,
        String    event,
        String    description,
        String    before,
        String    after
    ) {
        this.id = id;
        this.createdTs = createdTs;
        this.level = level;
        this.event = event;
        this.description = description;
        this.before = before;
        this.after = after;
    }

    public ULong getId() {
        return this.id;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public LogLevel getLevel() {
        return this.level;
    }

    public String getEvent() {
        return this.event;
    }

    public String getDescription() {
        return this.description;
    }

    public String getBefore() {
        return this.before;
    }

    public String getAfter() {
        return this.after;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Log (");

        sb.append(id);
        sb.append(", ").append(createdTs);
        sb.append(", ").append(level);
        sb.append(", ").append(event);
        sb.append(", ").append(description);
        sb.append(", ").append(before);
        sb.append(", ").append(after);

        sb.append(")");
        return sb.toString();
    }
}
