/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderTrackingInfo implements Serializable {

    private static final long serialVersionUID = -1211568833;

    private final ULong     id;
    private final ULong     orderId;
    private final String    trackingNumber;
    private final Timestamp createdTs;
    private final Timestamp updatedTs;

    public OrderTrackingInfo(OrderTrackingInfo value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.trackingNumber = value.trackingNumber;
        this.createdTs = value.createdTs;
        this.updatedTs = value.updatedTs;
    }

    public OrderTrackingInfo(
        ULong     id,
        ULong     orderId,
        String    trackingNumber,
        Timestamp createdTs,
        Timestamp updatedTs
    ) {
        this.id = id;
        this.orderId = orderId;
        this.trackingNumber = trackingNumber;
        this.createdTs = createdTs;
        this.updatedTs = updatedTs;
    }

    public ULong getId() {
        return this.id;
    }

    public ULong getOrderId() {
        return this.orderId;
    }

    public String getTrackingNumber() {
        return this.trackingNumber;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public Timestamp getUpdatedTs() {
        return this.updatedTs;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderTrackingInfo (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(trackingNumber);
        sb.append(", ").append(createdTs);
        sb.append(", ").append(updatedTs);

        sb.append(")");
        return sb.toString();
    }
}
