/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderItem implements Serializable {

    private static final long serialVersionUID = -847055681;

    private ULong      id;
    private ULong      orderId;
    private String     itemNumber;
    private String     itemDescription;
    private BigDecimal price;
    private BigDecimal quantity;
    private Byte       perishable;
    private Integer    discountPercent;
    private BigDecimal discountPrice;
    private String     promoCode;
    private BigDecimal weight;
    private String     weightUom;
    private Byte       isTaxable;
    private BigDecimal tax;
    private String     salesTaxCode;
    private ULong      promotionId;
    private BigDecimal qtyShip;
    private String     catchWeight;
    private BigDecimal catchWeightPrice;
    private BigDecimal refundAmount;
    private BigDecimal refundQty;
    private Timestamp  refundEmailTs;
    private Timestamp  createdTs;
    private Timestamp  updatedTs;

    public OrderItem() {}

    public OrderItem(OrderItem value) {
        this.id = value.id;
        this.orderId = value.orderId;
        this.itemNumber = value.itemNumber;
        this.itemDescription = value.itemDescription;
        this.price = value.price;
        this.quantity = value.quantity;
        this.perishable = value.perishable;
        this.discountPercent = value.discountPercent;
        this.discountPrice = value.discountPrice;
        this.promoCode = value.promoCode;
        this.weight = value.weight;
        this.weightUom = value.weightUom;
        this.isTaxable = value.isTaxable;
        this.tax = value.tax;
        this.salesTaxCode = value.salesTaxCode;
        this.promotionId = value.promotionId;
        this.qtyShip = value.qtyShip;
        this.catchWeight = value.catchWeight;
        this.catchWeightPrice = value.catchWeightPrice;
        this.refundAmount = value.refundAmount;
        this.refundQty = value.refundQty;
        this.refundEmailTs = value.refundEmailTs;
        this.createdTs = value.createdTs;
        this.updatedTs = value.updatedTs;
    }

    public OrderItem(
        ULong      id,
        ULong      orderId,
        String     itemNumber,
        String     itemDescription,
        BigDecimal price,
        BigDecimal quantity,
        Byte       perishable,
        Integer    discountPercent,
        BigDecimal discountPrice,
        String     promoCode,
        BigDecimal weight,
        String     weightUom,
        Byte       isTaxable,
        BigDecimal tax,
        String     salesTaxCode,
        ULong      promotionId,
        BigDecimal qtyShip,
        String     catchWeight,
        BigDecimal catchWeightPrice,
        BigDecimal refundAmount,
        BigDecimal refundQty,
        Timestamp  refundEmailTs,
        Timestamp  createdTs,
        Timestamp  updatedTs
    ) {
        this.id = id;
        this.orderId = orderId;
        this.itemNumber = itemNumber;
        this.itemDescription = itemDescription;
        this.price = price;
        this.quantity = quantity;
        this.perishable = perishable;
        this.discountPercent = discountPercent;
        this.discountPrice = discountPrice;
        this.promoCode = promoCode;
        this.weight = weight;
        this.weightUom = weightUom;
        this.isTaxable = isTaxable;
        this.tax = tax;
        this.salesTaxCode = salesTaxCode;
        this.promotionId = promotionId;
        this.qtyShip = qtyShip;
        this.catchWeight = catchWeight;
        this.catchWeightPrice = catchWeightPrice;
        this.refundAmount = refundAmount;
        this.refundQty = refundQty;
        this.refundEmailTs = refundEmailTs;
        this.createdTs = createdTs;
        this.updatedTs = updatedTs;
    }

    public ULong getId() {
        return this.id;
    }

    public OrderItem setId(ULong id) {
        this.id = id;
        return this;
    }

    public ULong getOrderId() {
        return this.orderId;
    }

    public OrderItem setOrderId(ULong orderId) {
        this.orderId = orderId;
        return this;
    }

    public String getItemNumber() {
        return this.itemNumber;
    }

    public OrderItem setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;
        return this;
    }

    public String getItemDescription() {
        return this.itemDescription;
    }

    public OrderItem setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
        return this;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public OrderItem setPrice(BigDecimal price) {
        this.price = price;
        return this;
    }

    public BigDecimal getQuantity() {
        return this.quantity;
    }

    public OrderItem setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
        return this;
    }

    public Byte getPerishable() {
        return this.perishable;
    }

    public OrderItem setPerishable(Byte perishable) {
        this.perishable = perishable;
        return this;
    }

    public Integer getDiscountPercent() {
        return this.discountPercent;
    }

    public OrderItem setDiscountPercent(Integer discountPercent) {
        this.discountPercent = discountPercent;
        return this;
    }

    public BigDecimal getDiscountPrice() {
        return this.discountPrice;
    }

    public OrderItem setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
        return this;
    }

    public String getPromoCode() {
        return this.promoCode;
    }

    public OrderItem setPromoCode(String promoCode) {
        this.promoCode = promoCode;
        return this;
    }

    public BigDecimal getWeight() {
        return this.weight;
    }

    public OrderItem setWeight(BigDecimal weight) {
        this.weight = weight;
        return this;
    }

    public String getWeightUom() {
        return this.weightUom;
    }

    public OrderItem setWeightUom(String weightUom) {
        this.weightUom = weightUom;
        return this;
    }

    public Byte getIsTaxable() {
        return this.isTaxable;
    }

    public OrderItem setIsTaxable(Byte isTaxable) {
        this.isTaxable = isTaxable;
        return this;
    }

    public BigDecimal getTax() {
        return this.tax;
    }

    public OrderItem setTax(BigDecimal tax) {
        this.tax = tax;
        return this;
    }

    public String getSalesTaxCode() {
        return this.salesTaxCode;
    }

    public OrderItem setSalesTaxCode(String salesTaxCode) {
        this.salesTaxCode = salesTaxCode;
        return this;
    }

    public ULong getPromotionId() {
        return this.promotionId;
    }

    public OrderItem setPromotionId(ULong promotionId) {
        this.promotionId = promotionId;
        return this;
    }

    public BigDecimal getQtyShip() {
        return this.qtyShip;
    }

    public OrderItem setQtyShip(BigDecimal qtyShip) {
        this.qtyShip = qtyShip;
        return this;
    }

    public String getCatchWeight() {
        return this.catchWeight;
    }

    public OrderItem setCatchWeight(String catchWeight) {
        this.catchWeight = catchWeight;
        return this;
    }

    public BigDecimal getCatchWeightPrice() {
        return this.catchWeightPrice;
    }

    public OrderItem setCatchWeightPrice(BigDecimal catchWeightPrice) {
        this.catchWeightPrice = catchWeightPrice;
        return this;
    }

    public BigDecimal getRefundAmount() {
        return this.refundAmount;
    }

    public OrderItem setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
        return this;
    }

    public BigDecimal getRefundQty() {
        return this.refundQty;
    }

    public OrderItem setRefundQty(BigDecimal refundQty) {
        this.refundQty = refundQty;
        return this;
    }

    public Timestamp getRefundEmailTs() {
        return this.refundEmailTs;
    }

    public OrderItem setRefundEmailTs(Timestamp refundEmailTs) {
        this.refundEmailTs = refundEmailTs;
        return this;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public OrderItem setCreatedTs(Timestamp createdTs) {
        this.createdTs = createdTs;
        return this;
    }

    public Timestamp getUpdatedTs() {
        return this.updatedTs;
    }

    public OrderItem setUpdatedTs(Timestamp updatedTs) {
        this.updatedTs = updatedTs;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderItem (");

        sb.append(id);
        sb.append(", ").append(orderId);
        sb.append(", ").append(itemNumber);
        sb.append(", ").append(itemDescription);
        sb.append(", ").append(price);
        sb.append(", ").append(quantity);
        sb.append(", ").append(perishable);
        sb.append(", ").append(discountPercent);
        sb.append(", ").append(discountPrice);
        sb.append(", ").append(promoCode);
        sb.append(", ").append(weight);
        sb.append(", ").append(weightUom);
        sb.append(", ").append(isTaxable);
        sb.append(", ").append(tax);
        sb.append(", ").append(salesTaxCode);
        sb.append(", ").append(promotionId);
        sb.append(", ").append(qtyShip);
        sb.append(", ").append(catchWeight);
        sb.append(", ").append(catchWeightPrice);
        sb.append(", ").append(refundAmount);
        sb.append(", ").append(refundQty);
        sb.append(", ").append(refundEmailTs);
        sb.append(", ").append(createdTs);
        sb.append(", ").append(updatedTs);

        sb.append(")");
        return sb.toString();
    }
}
