/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductAvailability implements Serializable {

    private static final long serialVersionUID = -938255736;

    private ULong   id;
    private String  itemNumber;
    private Integer s2kAvailable;
    private Integer availableQuantity;
    private Integer pendingSoldQuantity;
    private Integer confirmedSoldQuantity;

    public ProductAvailability() {}

    public ProductAvailability(ProductAvailability value) {
        this.id = value.id;
        this.itemNumber = value.itemNumber;
        this.s2kAvailable = value.s2kAvailable;
        this.availableQuantity = value.availableQuantity;
        this.pendingSoldQuantity = value.pendingSoldQuantity;
        this.confirmedSoldQuantity = value.confirmedSoldQuantity;
    }

    public ProductAvailability(
        ULong   id,
        String  itemNumber,
        Integer s2kAvailable,
        Integer availableQuantity,
        Integer pendingSoldQuantity,
        Integer confirmedSoldQuantity
    ) {
        this.id = id;
        this.itemNumber = itemNumber;
        this.s2kAvailable = s2kAvailable;
        this.availableQuantity = availableQuantity;
        this.pendingSoldQuantity = pendingSoldQuantity;
        this.confirmedSoldQuantity = confirmedSoldQuantity;
    }

    public ULong getId() {
        return this.id;
    }

    public ProductAvailability setId(ULong id) {
        this.id = id;
        return this;
    }

    public String getItemNumber() {
        return this.itemNumber;
    }

    public ProductAvailability setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;
        return this;
    }

    public Integer getS2kAvailable() {
        return this.s2kAvailable;
    }

    public ProductAvailability setS2kAvailable(Integer s2kAvailable) {
        this.s2kAvailable = s2kAvailable;
        return this;
    }

    public Integer getAvailableQuantity() {
        return this.availableQuantity;
    }

    public ProductAvailability setAvailableQuantity(Integer availableQuantity) {
        this.availableQuantity = availableQuantity;
        return this;
    }

    public Integer getPendingSoldQuantity() {
        return this.pendingSoldQuantity;
    }

    public ProductAvailability setPendingSoldQuantity(Integer pendingSoldQuantity) {
        this.pendingSoldQuantity = pendingSoldQuantity;
        return this;
    }

    public Integer getConfirmedSoldQuantity() {
        return this.confirmedSoldQuantity;
    }

    public ProductAvailability setConfirmedSoldQuantity(Integer confirmedSoldQuantity) {
        this.confirmedSoldQuantity = confirmedSoldQuantity;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductAvailability (");

        sb.append(id);
        sb.append(", ").append(itemNumber);
        sb.append(", ").append(s2kAvailable);
        sb.append(", ").append(availableQuantity);
        sb.append(", ").append(pendingSoldQuantity);
        sb.append(", ").append(confirmedSoldQuantity);

        sb.append(")");
        return sb.toString();
    }
}
