/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import com.scratch.database.mysql.jv.enums.PromotionDetailDetailType;
import com.scratch.database.mysql.jv.enums.PromotionDetailDiscountType;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PromotionDetail implements Serializable {

    private static final long serialVersionUID = -1558765977;

    private final ULong                       id;
    private final ULong                       promotionId;
    private final PromotionDetailDetailType   detailType;
    private final String                      key;
    private final PromotionDetailDiscountType discountType;
    private final BigDecimal                  discountAmount;
    private final Byte                        isDeleted;

    public PromotionDetail(PromotionDetail value) {
        this.id = value.id;
        this.promotionId = value.promotionId;
        this.detailType = value.detailType;
        this.key = value.key;
        this.discountType = value.discountType;
        this.discountAmount = value.discountAmount;
        this.isDeleted = value.isDeleted;
    }

    public PromotionDetail(
        ULong                       id,
        ULong                       promotionId,
        PromotionDetailDetailType   detailType,
        String                      key,
        PromotionDetailDiscountType discountType,
        BigDecimal                  discountAmount,
        Byte                        isDeleted
    ) {
        this.id = id;
        this.promotionId = promotionId;
        this.detailType = detailType;
        this.key = key;
        this.discountType = discountType;
        this.discountAmount = discountAmount;
        this.isDeleted = isDeleted;
    }

    public ULong getId() {
        return this.id;
    }

    public ULong getPromotionId() {
        return this.promotionId;
    }

    public PromotionDetailDetailType getDetailType() {
        return this.detailType;
    }

    public String getKey() {
        return this.key;
    }

    public PromotionDetailDiscountType getDiscountType() {
        return this.discountType;
    }

    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }

    public Byte getIsDeleted() {
        return this.isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PromotionDetail (");

        sb.append(id);
        sb.append(", ").append(promotionId);
        sb.append(", ").append(detailType);
        sb.append(", ").append(key);
        sb.append(", ").append(discountType);
        sb.append(", ").append(discountAmount);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
