/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeCategory implements Serializable {

    private static final long serialVersionUID = 442463970;

    private final ULong     id;
    private final String    url;
    private final String    name;
    private final String    description;
    private final Integer   sequence;
    private final Byte      isActive;
    private final Byte      isDeleted;
    private final Timestamp updatedTs;
    private final Timestamp createdTs;

    public RecipeCategory(RecipeCategory value) {
        this.id = value.id;
        this.url = value.url;
        this.name = value.name;
        this.description = value.description;
        this.sequence = value.sequence;
        this.isActive = value.isActive;
        this.isDeleted = value.isDeleted;
        this.updatedTs = value.updatedTs;
        this.createdTs = value.createdTs;
    }

    public RecipeCategory(
        ULong     id,
        String    url,
        String    name,
        String    description,
        Integer   sequence,
        Byte      isActive,
        Byte      isDeleted,
        Timestamp updatedTs,
        Timestamp createdTs
    ) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.description = description;
        this.sequence = sequence;
        this.isActive = isActive;
        this.isDeleted = isDeleted;
        this.updatedTs = updatedTs;
        this.createdTs = createdTs;
    }

    public ULong getId() {
        return this.id;
    }

    public String getUrl() {
        return this.url;
    }

    public String getName() {
        return this.name;
    }

    public String getDescription() {
        return this.description;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public Byte getIsActive() {
        return this.isActive;
    }

    public Byte getIsDeleted() {
        return this.isDeleted;
    }

    public Timestamp getUpdatedTs() {
        return this.updatedTs;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RecipeCategory (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(sequence);
        sb.append(", ").append(isActive);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(updatedTs);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
