/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeCategory implements Serializable {

    private static final long serialVersionUID = 986820871;

    private ULong     id;
    private String    url;
    private String    name;
    private String    description;
    private Integer   sequence;
    private Byte      isActive;
    private Byte      isDeleted;
    private Timestamp updatedTs;
    private Timestamp createdTs;

    public RecipeCategory() {}

    public RecipeCategory(RecipeCategory value) {
        this.id = value.id;
        this.url = value.url;
        this.name = value.name;
        this.description = value.description;
        this.sequence = value.sequence;
        this.isActive = value.isActive;
        this.isDeleted = value.isDeleted;
        this.updatedTs = value.updatedTs;
        this.createdTs = value.createdTs;
    }

    public RecipeCategory(
        ULong     id,
        String    url,
        String    name,
        String    description,
        Integer   sequence,
        Byte      isActive,
        Byte      isDeleted,
        Timestamp updatedTs,
        Timestamp createdTs
    ) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.description = description;
        this.sequence = sequence;
        this.isActive = isActive;
        this.isDeleted = isDeleted;
        this.updatedTs = updatedTs;
        this.createdTs = createdTs;
    }

    public ULong getId() {
        return this.id;
    }

    public RecipeCategory setId(ULong id) {
        this.id = id;
        return this;
    }

    public String getUrl() {
        return this.url;
    }

    public RecipeCategory setUrl(String url) {
        this.url = url;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public RecipeCategory setName(String name) {
        this.name = name;
        return this;
    }

    public String getDescription() {
        return this.description;
    }

    public RecipeCategory setDescription(String description) {
        this.description = description;
        return this;
    }

    public Integer getSequence() {
        return this.sequence;
    }

    public RecipeCategory setSequence(Integer sequence) {
        this.sequence = sequence;
        return this;
    }

    public Byte getIsActive() {
        return this.isActive;
    }

    public RecipeCategory setIsActive(Byte isActive) {
        this.isActive = isActive;
        return this;
    }

    public Byte getIsDeleted() {
        return this.isDeleted;
    }

    public RecipeCategory setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
        return this;
    }

    public Timestamp getUpdatedTs() {
        return this.updatedTs;
    }

    public RecipeCategory setUpdatedTs(Timestamp updatedTs) {
        this.updatedTs = updatedTs;
        return this;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public RecipeCategory setCreatedTs(Timestamp createdTs) {
        this.createdTs = createdTs;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RecipeCategory (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(sequence);
        sb.append(", ").append(isActive);
        sb.append(", ").append(isDeleted);
        sb.append(", ").append(updatedTs);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
