/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedItems implements Serializable {

    private static final long serialVersionUID = -1964346211;

    private ULong     id;
    private String    itemNumber;
    private String    relatedItemNumber;
    private ULong     sequenceNumber;
    private Timestamp updatedTs;
    private Timestamp createdTs;

    public RelatedItems() {}

    public RelatedItems(RelatedItems value) {
        this.id = value.id;
        this.itemNumber = value.itemNumber;
        this.relatedItemNumber = value.relatedItemNumber;
        this.sequenceNumber = value.sequenceNumber;
        this.updatedTs = value.updatedTs;
        this.createdTs = value.createdTs;
    }

    public RelatedItems(
        ULong     id,
        String    itemNumber,
        String    relatedItemNumber,
        ULong     sequenceNumber,
        Timestamp updatedTs,
        Timestamp createdTs
    ) {
        this.id = id;
        this.itemNumber = itemNumber;
        this.relatedItemNumber = relatedItemNumber;
        this.sequenceNumber = sequenceNumber;
        this.updatedTs = updatedTs;
        this.createdTs = createdTs;
    }

    public ULong getId() {
        return this.id;
    }

    public RelatedItems setId(ULong id) {
        this.id = id;
        return this;
    }

    public String getItemNumber() {
        return this.itemNumber;
    }

    public RelatedItems setItemNumber(String itemNumber) {
        this.itemNumber = itemNumber;
        return this;
    }

    public String getRelatedItemNumber() {
        return this.relatedItemNumber;
    }

    public RelatedItems setRelatedItemNumber(String relatedItemNumber) {
        this.relatedItemNumber = relatedItemNumber;
        return this;
    }

    public ULong getSequenceNumber() {
        return this.sequenceNumber;
    }

    public RelatedItems setSequenceNumber(ULong sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
        return this;
    }

    public Timestamp getUpdatedTs() {
        return this.updatedTs;
    }

    public RelatedItems setUpdatedTs(Timestamp updatedTs) {
        this.updatedTs = updatedTs;
        return this;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public RelatedItems setCreatedTs(Timestamp createdTs) {
        this.createdTs = createdTs;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("RelatedItems (");

        sb.append(id);
        sb.append(", ").append(itemNumber);
        sb.append(", ").append(relatedItemNumber);
        sb.append(", ").append(sequenceNumber);
        sb.append(", ").append(updatedTs);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
