/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import com.scratch.database.mysql.jv.enums.S2kOrderStatusCodeCode;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S2kOrderStatusCode implements Serializable {

    private static final long serialVersionUID = -1102799020;

    private final Integer                id;
    private final S2kOrderStatusCodeCode code;
    private final String                 name;

    public S2kOrderStatusCode(S2kOrderStatusCode value) {
        this.id = value.id;
        this.code = value.code;
        this.name = value.name;
    }

    public S2kOrderStatusCode(
        Integer                id,
        S2kOrderStatusCodeCode code,
        String                 name
    ) {
        this.id = id;
        this.code = code;
        this.name = name;
    }

    public Integer getId() {
        return this.id;
    }

    public S2kOrderStatusCodeCode getCode() {
        return this.code;
    }

    public String getName() {
        return this.name;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("S2kOrderStatusCode (");

        sb.append(id);
        sb.append(", ").append(code);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }
}
