/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Session implements Serializable {

    private static final long serialVersionUID = -512607006;

    private final String  id;
    private final String  name;
    private final Integer modified;
    private final Integer lifetime;
    private final String  data;

    public Session(Session value) {
        this.id = value.id;
        this.name = value.name;
        this.modified = value.modified;
        this.lifetime = value.lifetime;
        this.data = value.data;
    }

    public Session(
        String  id,
        String  name,
        Integer modified,
        Integer lifetime,
        String  data
    ) {
        this.id = id;
        this.name = name;
        this.modified = modified;
        this.lifetime = lifetime;
        this.data = data;
    }

    public String getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public Integer getModified() {
        return this.modified;
    }

    public Integer getLifetime() {
        return this.lifetime;
    }

    public String getData() {
        return this.data;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Session (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(modified);
        sb.append(", ").append(lifetime);
        sb.append(", ").append(data);

        sb.append(")");
        return sb.toString();
    }
}
