/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import com.scratch.database.mysql.jv.enums.TagRelationType;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagRelation implements Serializable {

    private static final long serialVersionUID = -688106122;

    private final ULong           id;
    private final TagRelationType type;
    private final ULong           tagId;
    private final String          relatedId;
    private final Timestamp       createdTs;

    public TagRelation(TagRelation value) {
        this.id = value.id;
        this.type = value.type;
        this.tagId = value.tagId;
        this.relatedId = value.relatedId;
        this.createdTs = value.createdTs;
    }

    public TagRelation(
        ULong           id,
        TagRelationType type,
        ULong           tagId,
        String          relatedId,
        Timestamp       createdTs
    ) {
        this.id = id;
        this.type = type;
        this.tagId = tagId;
        this.relatedId = relatedId;
        this.createdTs = createdTs;
    }

    public ULong getId() {
        return this.id;
    }

    public TagRelationType getType() {
        return this.type;
    }

    public ULong getTagId() {
        return this.tagId;
    }

    public String getRelatedId() {
        return this.relatedId;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TagRelation (");

        sb.append(id);
        sb.append(", ").append(type);
        sb.append(", ").append(tagId);
        sb.append(", ").append(relatedId);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
