/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uom implements Serializable {

    private static final long serialVersionUID = -1650157847;

    private final String    id;
    private final String    name;
    private final Timestamp createdTs;

    public Uom(Uom value) {
        this.id = value.id;
        this.name = value.name;
        this.createdTs = value.createdTs;
    }

    public Uom(
        String    id,
        String    name,
        Timestamp createdTs
    ) {
        this.id = id;
        this.name = name;
        this.createdTs = createdTs;
    }

    public String getId() {
        return this.id;
    }

    public String getName() {
        return this.name;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Uom (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
