/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uom implements Serializable {

    private static final long serialVersionUID = -407960286;

    private String    id;
    private String    name;
    private Timestamp createdTs;

    public Uom() {}

    public Uom(Uom value) {
        this.id = value.id;
        this.name = value.name;
        this.createdTs = value.createdTs;
    }

    public Uom(
        String    id,
        String    name,
        Timestamp createdTs
    ) {
        this.id = id;
        this.name = name;
        this.createdTs = createdTs;
    }

    public String getId() {
        return this.id;
    }

    public Uom setId(String id) {
        this.id = id;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public Uom setName(String name) {
        this.name = name;
        return this;
    }

    public Timestamp getCreatedTs() {
        return this.createdTs;
    }

    public Uom setCreatedTs(Timestamp createdTs) {
        this.createdTs = createdTs;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Uom (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(createdTs);

        sb.append(")");
        return sb.toString();
    }
}
