/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.tables.AccountFilter;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountFilterRecord extends UpdatableRecordImpl<AccountFilterRecord> implements Record3<ULong, ULong, ULong> {

    private static final long serialVersionUID = -1215025751;

    /**
     * Setter for <code>jv_b2c_dev.account_filter.id</code>.
     */
    public AccountFilterRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.account_filter.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.account_filter.account_id</code>.
     */
    public AccountFilterRecord setAccountId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.account_filter.account_id</code>.
     */
    public ULong getAccountId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.account_filter.tag_id</code>.
     */
    public AccountFilterRecord setTagId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.account_filter.tag_id</code>.
     */
    public ULong getTagId() {
        return (ULong) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, ULong, ULong> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<ULong, ULong, ULong> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return AccountFilter.ACCOUNT_FILTER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return AccountFilter.ACCOUNT_FILTER.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return AccountFilter.ACCOUNT_FILTER.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountFilterRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountFilterRecord value2(ULong value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountFilterRecord value3(ULong value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountFilterRecord values(ULong value1, ULong value2, ULong value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountFilterRecord
     */
    public AccountFilterRecord() {
        super(AccountFilter.ACCOUNT_FILTER);
    }

    /**
     * Create a detached, initialised AccountFilterRecord
     */
    public AccountFilterRecord(ULong id, ULong accountId, ULong tagId) {
        super(AccountFilter.ACCOUNT_FILTER);

        set(0, id);
        set(1, accountId);
        set(2, tagId);
    }
}
