/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.tables.Banner;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BannerRecord extends UpdatableRecordImpl<BannerRecord> implements Record7<ULong, Byte, String, ULong, ULong, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1960938882;

    /**
     * Setter for <code>jv_b2c_dev.banner.id</code>.
     */
    public BannerRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.banner.is_active</code>.
     */
    public BannerRecord setIsActive(Byte value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.banner.display_text</code>.
     */
    public BannerRecord setDisplayText(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.display_text</code>.
     */
    public String getDisplayText() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jv_b2c_dev.banner.content_id</code>.
     */
    public BannerRecord setContentId(ULong value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.content_id</code>.
     */
    public ULong getContentId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>jv_b2c_dev.banner.promotion_id</code>.
     */
    public BannerRecord setPromotionId(ULong value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.promotion_id</code>.
     */
    public ULong getPromotionId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>jv_b2c_dev.banner.created_ts</code>.
     */
    public BannerRecord setCreatedTs(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.created_ts</code>.
     */
    public Timestamp getCreatedTs() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>jv_b2c_dev.banner.updated_ts</code>.
     */
    public BannerRecord setUpdatedTs(Timestamp value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.banner.updated_ts</code>.
     */
    public Timestamp getUpdatedTs() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, Byte, String, ULong, ULong, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, Byte, String, ULong, ULong, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Banner.BANNER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return Banner.BANNER.IS_ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Banner.BANNER.DISPLAY_TEXT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field4() {
        return Banner.BANNER.CONTENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field5() {
        return Banner.BANNER.PROMOTION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Banner.BANNER.CREATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Banner.BANNER.UPDATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDisplayText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component4() {
        return getContentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component5() {
        return getPromotionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisplayText();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value4() {
        return getContentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value5() {
        return getPromotionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value2(Byte value) {
        setIsActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value3(String value) {
        setDisplayText(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value4(ULong value) {
        setContentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value5(ULong value) {
        setPromotionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value6(Timestamp value) {
        setCreatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord value7(Timestamp value) {
        setUpdatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BannerRecord values(ULong value1, Byte value2, String value3, ULong value4, ULong value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BannerRecord
     */
    public BannerRecord() {
        super(Banner.BANNER);
    }

    /**
     * Create a detached, initialised BannerRecord
     */
    public BannerRecord(ULong id, Byte isActive, String displayText, ULong contentId, ULong promotionId, Timestamp createdTs, Timestamp updatedTs) {
        super(Banner.BANNER);

        set(0, id);
        set(1, isActive);
        set(2, displayText);
        set(3, contentId);
        set(4, promotionId);
        set(5, createdTs);
        set(6, updatedTs);
    }
}
