/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.enums.CartShippingPromotionType;
import com.scratch.database.mysql.jv.tables.Cart;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CartRecord extends UpdatableRecordImpl<CartRecord> implements Record14<ULong, String, ULong, String, BigDecimal, BigDecimal, UInteger, BigDecimal, String, CartShippingPromotionType, BigDecimal, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -898241751;

    /**
     * Setter for <code>jv_b2c_dev.cart.id</code>.
     */
    public CartRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.session_id</code>.
     */
    public CartRecord setSessionId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.session_id</code>.
     */
    public String getSessionId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.user_id</code>.
     */
    public CartRecord setUserId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.item_number</code>.
     */
    public CartRecord setItemNumber(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.item_number</code>.
     */
    public String getItemNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.price</code>.
     */
    public CartRecord setPrice(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.price</code>.
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.quantity</code>.
     */
    public CartRecord setQuantity(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.discount_percent</code>.
     */
    public CartRecord setDiscountPercent(UInteger value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.discount_percent</code>.
     */
    public UInteger getDiscountPercent() {
        return (UInteger) get(6);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.discount_price</code>.
     */
    public CartRecord setDiscountPrice(BigDecimal value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.discount_price</code>.
     */
    public BigDecimal getDiscountPrice() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.promo_code</code>.
     */
    public CartRecord setPromoCode(String value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.promo_code</code>.
     */
    public String getPromoCode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.shipping_promotion_type</code>.
     */
    public CartRecord setShippingPromotionType(CartShippingPromotionType value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.shipping_promotion_type</code>.
     */
    public CartShippingPromotionType getShippingPromotionType() {
        return (CartShippingPromotionType) get(9);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.shipping_promotion_amount</code>.
     */
    public CartRecord setShippingPromotionAmount(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.shipping_promotion_amount</code>.
     */
    public BigDecimal getShippingPromotionAmount() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.shipping_promotion_method</code>.
     */
    public CartRecord setShippingPromotionMethod(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.shipping_promotion_method</code>.
     */
    public String getShippingPromotionMethod() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.updated_ts</code>.
     */
    public CartRecord setUpdatedTs(Timestamp value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.updated_ts</code>.
     */
    public Timestamp getUpdatedTs() {
        return (Timestamp) get(12);
    }

    /**
     * Setter for <code>jv_b2c_dev.cart.created_ts</code>.
     */
    public CartRecord setCreatedTs(Timestamp value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.cart.created_ts</code>.
     */
    public Timestamp getCreatedTs() {
        return (Timestamp) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<ULong, String, ULong, String, BigDecimal, BigDecimal, UInteger, BigDecimal, String, CartShippingPromotionType, BigDecimal, String, Timestamp, Timestamp> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<ULong, String, ULong, String, BigDecimal, BigDecimal, UInteger, BigDecimal, String, CartShippingPromotionType, BigDecimal, String, Timestamp, Timestamp> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return Cart.CART.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cart.CART.SESSION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return Cart.CART.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Cart.CART.ITEM_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return Cart.CART.PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return Cart.CART.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return Cart.CART.DISCOUNT_PERCENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return Cart.CART.DISCOUNT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Cart.CART.PROMO_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<CartShippingPromotionType> field10() {
        return Cart.CART.SHIPPING_PROMOTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return Cart.CART.SHIPPING_PROMOTION_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Cart.CART.SHIPPING_PROMOTION_METHOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field13() {
        return Cart.CART.UPDATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return Cart.CART.CREATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getItemNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getDiscountPercent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getPromoCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartShippingPromotionType component10() {
        return getShippingPromotionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getShippingPromotionAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getShippingPromotionMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component13() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSessionId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getItemNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getDiscountPercent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getPromoCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartShippingPromotionType value10() {
        return getShippingPromotionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getShippingPromotionAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getShippingPromotionMethod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value13() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value2(String value) {
        setSessionId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value3(ULong value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value4(String value) {
        setItemNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value5(BigDecimal value) {
        setPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value6(BigDecimal value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value7(UInteger value) {
        setDiscountPercent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value8(BigDecimal value) {
        setDiscountPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value9(String value) {
        setPromoCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value10(CartShippingPromotionType value) {
        setShippingPromotionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value11(BigDecimal value) {
        setShippingPromotionAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value12(String value) {
        setShippingPromotionMethod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value13(Timestamp value) {
        setUpdatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord value14(Timestamp value) {
        setCreatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CartRecord values(ULong value1, String value2, ULong value3, String value4, BigDecimal value5, BigDecimal value6, UInteger value7, BigDecimal value8, String value9, CartShippingPromotionType value10, BigDecimal value11, String value12, Timestamp value13, Timestamp value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CartRecord
     */
    public CartRecord() {
        super(Cart.CART);
    }

    /**
     * Create a detached, initialised CartRecord
     */
    public CartRecord(ULong id, String sessionId, ULong userId, String itemNumber, BigDecimal price, BigDecimal quantity, UInteger discountPercent, BigDecimal discountPrice, String promoCode, CartShippingPromotionType shippingPromotionType, BigDecimal shippingPromotionAmount, String shippingPromotionMethod, Timestamp updatedTs, Timestamp createdTs) {
        super(Cart.CART);

        set(0, id);
        set(1, sessionId);
        set(2, userId);
        set(3, itemNumber);
        set(4, price);
        set(5, quantity);
        set(6, discountPercent);
        set(7, discountPrice);
        set(8, promoCode);
        set(9, shippingPromotionType);
        set(10, shippingPromotionAmount);
        set(11, shippingPromotionMethod);
        set(12, updatedTs);
        set(13, createdTs);
    }
}
