/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.tables.CategoryRelation;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CategoryRelationRecord extends UpdatableRecordImpl<CategoryRelationRecord> implements Record6<ULong, ULong, ULong, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1818822319;

    /**
     * Setter for <code>jv_b2c_dev.category_relation.id</code>.
     */
    public CategoryRelationRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.category_relation.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.category_relation.category_id</code>.
     */
    public CategoryRelationRecord setCategoryId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.category_relation.category_id</code>.
     */
    public ULong getCategoryId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.category_relation.parent_id</code>.
     */
    public CategoryRelationRecord setParentId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.category_relation.parent_id</code>.
     */
    public ULong getParentId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>jv_b2c_dev.category_relation.sequence</code>.
     */
    public CategoryRelationRecord setSequence(Integer value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.category_relation.sequence</code>.
     */
    public Integer getSequence() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jv_b2c_dev.category_relation.updated_ts</code>.
     */
    public CategoryRelationRecord setUpdatedTs(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.category_relation.updated_ts</code>.
     */
    public Timestamp getUpdatedTs() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>jv_b2c_dev.category_relation.created_ts</code>.
     */
    public CategoryRelationRecord setCreatedTs(Timestamp value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.category_relation.created_ts</code>.
     */
    public Timestamp getCreatedTs() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, ULong, ULong, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<ULong, ULong, ULong, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return CategoryRelation.CATEGORY_RELATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return CategoryRelation.CATEGORY_RELATION.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return CategoryRelation.CATEGORY_RELATION.PARENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return CategoryRelation.CATEGORY_RELATION.SEQUENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return CategoryRelation.CATEGORY_RELATION.UPDATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return CategoryRelation.CATEGORY_RELATION.CREATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSequence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getParentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSequence();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord value2(ULong value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord value3(ULong value) {
        setParentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord value4(Integer value) {
        setSequence(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord value5(Timestamp value) {
        setUpdatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord value6(Timestamp value) {
        setCreatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CategoryRelationRecord values(ULong value1, ULong value2, ULong value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CategoryRelationRecord
     */
    public CategoryRelationRecord() {
        super(CategoryRelation.CATEGORY_RELATION);
    }

    /**
     * Create a detached, initialised CategoryRelationRecord
     */
    public CategoryRelationRecord(ULong id, ULong categoryId, ULong parentId, Integer sequence, Timestamp updatedTs, Timestamp createdTs) {
        super(CategoryRelation.CATEGORY_RELATION);

        set(0, id);
        set(1, categoryId);
        set(2, parentId);
        set(3, sequence);
        set(4, updatedTs);
        set(5, createdTs);
    }
}
