/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.tables.Product;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> {

    private static final long serialVersionUID = -1413948024;

    /**
     * Setter for <code>jv_b2c_dev.product.id</code>.
     */
    public ProductRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.item_number</code>.
     */
    public ProductRecord setItemNumber(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.item_number</code>.
     */
    public String getItemNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.description_1</code>.
     */
    public ProductRecord setDescription_1(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.description_1</code>.
     */
    public String getDescription_1() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.description_2</code>.
     */
    public ProductRecord setDescription_2(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.description_2</code>.
     */
    public String getDescription_2() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.uom</code>.
     */
    public ProductRecord setUom(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.uom</code>.
     */
    public String getUom() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.package_size</code>.
     */
    public ProductRecord setPackageSize(String value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.package_size</code>.
     */
    public String getPackageSize() {
        return (String) get(5);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.brand</code>.
     */
    public ProductRecord setBrand(String value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.brand</code>.
     */
    public String getBrand() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.brand_name</code>.
     */
    public ProductRecord setBrandName(String value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.brand_name</code>.
     */
    public String getBrandName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.perishable</code>.
     */
    public ProductRecord setPerishable(Byte value) {
        set(8, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.perishable</code>.
     */
    public Byte getPerishable() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.sales_tax_code</code>.
     */
    public ProductRecord setSalesTaxCode(String value) {
        set(9, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.sales_tax_code</code>.
     */
    public String getSalesTaxCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.item_weight</code>.
     */
    public ProductRecord setItemWeight(BigDecimal value) {
        set(10, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.item_weight</code>.
     */
    public BigDecimal getItemWeight() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.item_weight_uom</code>.
     */
    public ProductRecord setItemWeightUom(String value) {
        set(11, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.item_weight_uom</code>.
     */
    public String getItemWeightUom() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.short_description</code>.
     */
    public ProductRecord setShortDescription(String value) {
        set(12, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.short_description</code>.
     */
    public String getShortDescription() {
        return (String) get(12);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.long_description</code>.
     */
    public ProductRecord setLongDescription(String value) {
        set(13, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.long_description</code>.
     */
    public String getLongDescription() {
        return (String) get(13);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.replacement_item_number</code>.
     */
    public ProductRecord setReplacementItemNumber(String value) {
        set(14, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.replacement_item_number</code>.
     */
    public String getReplacementItemNumber() {
        return (String) get(14);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.display_name</code>.
     */
    public ProductRecord setDisplayName(String value) {
        set(15, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.url</code>.
     */
    public ProductRecord setUrl(String value) {
        set(16, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.url</code>.
     */
    public String getUrl() {
        return (String) get(16);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.meta_title</code>.
     */
    public ProductRecord setMetaTitle(String value) {
        set(17, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.meta_title</code>.
     */
    public String getMetaTitle() {
        return (String) get(17);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.meta_description</code>.
     */
    public ProductRecord setMetaDescription(String value) {
        set(18, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.meta_description</code>.
     */
    public String getMetaDescription() {
        return (String) get(18);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.is_giftable</code>.
     */
    public ProductRecord setIsGiftable(Byte value) {
        set(19, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.is_giftable</code>.
     */
    public Byte getIsGiftable() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.is_promotable</code>.
     */
    public ProductRecord setIsPromotable(Byte value) {
        set(20, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.is_promotable</code>.
     */
    public Byte getIsPromotable() {
        return (Byte) get(20);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.is_deleted</code>.
     */
    public ProductRecord setIsDeleted(Byte value) {
        set(21, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.is_deleted</code>.
     */
    public Byte getIsDeleted() {
        return (Byte) get(21);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.is_active</code>.
     */
    public ProductRecord setIsActive(Byte value) {
        set(22, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.is_active</code>.
     */
    public Byte getIsActive() {
        return (Byte) get(22);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.updated_ts</code>.
     */
    public ProductRecord setUpdatedTs(Timestamp value) {
        set(23, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.updated_ts</code>.
     */
    public Timestamp getUpdatedTs() {
        return (Timestamp) get(23);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.created_ts</code>.
     */
    public ProductRecord setCreatedTs(Timestamp value) {
        set(24, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.created_ts</code>.
     */
    public Timestamp getCreatedTs() {
        return (Timestamp) get(24);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.cubic_volume</code>.
     */
    public ProductRecord setCubicVolume(BigDecimal value) {
        set(25, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.cubic_volume</code>.
     */
    public BigDecimal getCubicVolume() {
        return (BigDecimal) get(25);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.cubic_volume_uom</code>.
     */
    public ProductRecord setCubicVolumeUom(String value) {
        set(26, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.cubic_volume_uom</code>.
     */
    public String getCubicVolumeUom() {
        return (String) get(26);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.catch_weight</code>.
     */
    public ProductRecord setCatchWeight(String value) {
        set(27, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.catch_weight</code>.
     */
    public String getCatchWeight() {
        return (String) get(27);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.catch_weight_UOM</code>.
     */
    public ProductRecord setCatchWeightUom(String value) {
        set(28, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.catch_weight_UOM</code>.
     */
    public String getCatchWeightUom() {
        return (String) get(28);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.average_weight</code>.
     */
    public ProductRecord setAverageWeight(BigDecimal value) {
        set(29, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.average_weight</code>.
     */
    public BigDecimal getAverageWeight() {
        return (BigDecimal) get(29);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.variance_over</code>.
     */
    public ProductRecord setVarianceOver(BigDecimal value) {
        set(30, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.variance_over</code>.
     */
    public BigDecimal getVarianceOver() {
        return (BigDecimal) get(30);
    }

    /**
     * Setter for <code>jv_b2c_dev.product.variance_under</code>.
     */
    public ProductRecord setVarianceUnder(BigDecimal value) {
        set(31, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.product.variance_under</code>.
     */
    public BigDecimal getVarianceUnder() {
        return (BigDecimal) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(ULong id, String itemNumber, String description_1, String description_2, String uom, String packageSize, String brand, String brandName, Byte perishable, String salesTaxCode, BigDecimal itemWeight, String itemWeightUom, String shortDescription, String longDescription, String replacementItemNumber, String displayName, String url, String metaTitle, String metaDescription, Byte isGiftable, Byte isPromotable, Byte isDeleted, Byte isActive, Timestamp updatedTs, Timestamp createdTs, BigDecimal cubicVolume, String cubicVolumeUom, String catchWeight, String catchWeightUom, BigDecimal averageWeight, BigDecimal varianceOver, BigDecimal varianceUnder) {
        super(Product.PRODUCT);

        set(0, id);
        set(1, itemNumber);
        set(2, description_1);
        set(3, description_2);
        set(4, uom);
        set(5, packageSize);
        set(6, brand);
        set(7, brandName);
        set(8, perishable);
        set(9, salesTaxCode);
        set(10, itemWeight);
        set(11, itemWeightUom);
        set(12, shortDescription);
        set(13, longDescription);
        set(14, replacementItemNumber);
        set(15, displayName);
        set(16, url);
        set(17, metaTitle);
        set(18, metaDescription);
        set(19, isGiftable);
        set(20, isPromotable);
        set(21, isDeleted);
        set(22, isActive);
        set(23, updatedTs);
        set(24, createdTs);
        set(25, cubicVolume);
        set(26, cubicVolumeUom);
        set(27, catchWeight);
        set(28, catchWeightUom);
        set(29, averageWeight);
        set(30, varianceOver);
        set(31, varianceUnder);
    }
}
