/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.tables.RecipeCategoryRelation;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecipeCategoryRelationRecord extends UpdatableRecordImpl<RecipeCategoryRelationRecord> implements Record5<ULong, ULong, ULong, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1588277808;

    /**
     * Setter for <code>jv_b2c_dev.recipe_category_relation.id</code>.
     */
    public RecipeCategoryRelationRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.recipe_category_relation.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.recipe_category_relation.recipe_id</code>.
     */
    public RecipeCategoryRelationRecord setRecipeId(ULong value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.recipe_category_relation.recipe_id</code>.
     */
    public ULong getRecipeId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.recipe_category_relation.category_id</code>.
     */
    public RecipeCategoryRelationRecord setCategoryId(ULong value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.recipe_category_relation.category_id</code>.
     */
    public ULong getCategoryId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>jv_b2c_dev.recipe_category_relation.updated_ts</code>.
     */
    public RecipeCategoryRelationRecord setUpdatedTs(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.recipe_category_relation.updated_ts</code>.
     */
    public Timestamp getUpdatedTs() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>jv_b2c_dev.recipe_category_relation.created_ts</code>.
     */
    public RecipeCategoryRelationRecord setCreatedTs(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.recipe_category_relation.created_ts</code>.
     */
    public Timestamp getCreatedTs() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, ULong, ULong, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, ULong, ULong, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return RecipeCategoryRelation.RECIPE_CATEGORY_RELATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field2() {
        return RecipeCategoryRelation.RECIPE_CATEGORY_RELATION.RECIPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field3() {
        return RecipeCategoryRelation.RECIPE_CATEGORY_RELATION.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return RecipeCategoryRelation.RECIPE_CATEGORY_RELATION.UPDATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return RecipeCategoryRelation.RECIPE_CATEGORY_RELATION.CREATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component2() {
        return getRecipeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value2() {
        return getRecipeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeCategoryRelationRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeCategoryRelationRecord value2(ULong value) {
        setRecipeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeCategoryRelationRecord value3(ULong value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeCategoryRelationRecord value4(Timestamp value) {
        setUpdatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeCategoryRelationRecord value5(Timestamp value) {
        setCreatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RecipeCategoryRelationRecord values(ULong value1, ULong value2, ULong value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipeCategoryRelationRecord
     */
    public RecipeCategoryRelationRecord() {
        super(RecipeCategoryRelation.RECIPE_CATEGORY_RELATION);
    }

    /**
     * Create a detached, initialised RecipeCategoryRelationRecord
     */
    public RecipeCategoryRelationRecord(ULong id, ULong recipeId, ULong categoryId, Timestamp updatedTs, Timestamp createdTs) {
        super(RecipeCategoryRelation.RECIPE_CATEGORY_RELATION);

        set(0, id);
        set(1, recipeId);
        set(2, categoryId);
        set(3, updatedTs);
        set(4, createdTs);
    }
}
