/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.enums.S2kOrderStatusCodeCode;
import com.scratch.database.mysql.jv.tables.S2kOrderStatusCode;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S2kOrderStatusCodeRecord extends UpdatableRecordImpl<S2kOrderStatusCodeRecord> implements Record3<Integer, S2kOrderStatusCodeCode, String> {

    private static final long serialVersionUID = 1569368717;

    /**
     * Setter for <code>jv_b2c_dev.s2k_order_status_code.id</code>.
     */
    public S2kOrderStatusCodeRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.s2k_order_status_code.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.s2k_order_status_code.code</code>.
     */
    public S2kOrderStatusCodeRecord setCode(S2kOrderStatusCodeCode value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.s2k_order_status_code.code</code>.
     */
    public S2kOrderStatusCodeCode getCode() {
        return (S2kOrderStatusCodeCode) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.s2k_order_status_code.name</code>.
     */
    public S2kOrderStatusCodeRecord setName(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.s2k_order_status_code.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, S2kOrderStatusCodeCode, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, S2kOrderStatusCodeCode, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return S2kOrderStatusCode.S2K_ORDER_STATUS_CODE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<S2kOrderStatusCodeCode> field2() {
        return S2kOrderStatusCode.S2K_ORDER_STATUS_CODE.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return S2kOrderStatusCode.S2K_ORDER_STATUS_CODE.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCodeCode component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCodeCode value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCodeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCodeRecord value2(S2kOrderStatusCodeCode value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCodeRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCodeRecord values(Integer value1, S2kOrderStatusCodeCode value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached S2kOrderStatusCodeRecord
     */
    public S2kOrderStatusCodeRecord() {
        super(S2kOrderStatusCode.S2K_ORDER_STATUS_CODE);
    }

    /**
     * Create a detached, initialised S2kOrderStatusCodeRecord
     */
    public S2kOrderStatusCodeRecord(Integer id, S2kOrderStatusCodeCode code, String name) {
        super(S2kOrderStatusCode.S2K_ORDER_STATUS_CODE);

        set(0, id);
        set(1, code);
        set(2, name);
    }
}
