/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables.records;


import com.scratch.database.mysql.jv.tables.SearchKeyword;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SearchKeywordRecord extends UpdatableRecordImpl<SearchKeywordRecord> implements Record5<ULong, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1904016886;

    /**
     * Setter for <code>jv_b2c_dev.search_keyword.id</code>.
     */
    public SearchKeywordRecord setId(ULong value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.search_keyword.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>jv_b2c_dev.search_keyword.search_keyword</code>.
     */
    public SearchKeywordRecord setSearchKeyword(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.search_keyword.search_keyword</code>.
     */
    public String getSearchKeyword() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jv_b2c_dev.search_keyword.replacement_keyword</code>.
     */
    public SearchKeywordRecord setReplacementKeyword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.search_keyword.replacement_keyword</code>.
     */
    public String getReplacementKeyword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jv_b2c_dev.search_keyword.created_ts</code>.
     */
    public SearchKeywordRecord setCreatedTs(Timestamp value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.search_keyword.created_ts</code>.
     */
    public Timestamp getCreatedTs() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>jv_b2c_dev.search_keyword.updated_ts</code>.
     */
    public SearchKeywordRecord setUpdatedTs(Timestamp value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>jv_b2c_dev.search_keyword.updated_ts</code>.
     */
    public Timestamp getUpdatedTs() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<ULong, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return SearchKeyword.SEARCH_KEYWORD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SearchKeyword.SEARCH_KEYWORD.SEARCH_KEYWORD_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SearchKeyword.SEARCH_KEYWORD.REPLACEMENT_KEYWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return SearchKeyword.SEARCH_KEYWORD.CREATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SearchKeyword.SEARCH_KEYWORD.UPDATED_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSearchKeyword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getReplacementKeyword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSearchKeyword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getReplacementKeyword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SearchKeywordRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SearchKeywordRecord value2(String value) {
        setSearchKeyword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SearchKeywordRecord value3(String value) {
        setReplacementKeyword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SearchKeywordRecord value4(Timestamp value) {
        setCreatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SearchKeywordRecord value5(Timestamp value) {
        setUpdatedTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SearchKeywordRecord values(ULong value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SearchKeywordRecord
     */
    public SearchKeywordRecord() {
        super(SearchKeyword.SEARCH_KEYWORD);
    }

    /**
     * Create a detached, initialised SearchKeywordRecord
     */
    public SearchKeywordRecord(ULong id, String searchKeyword, String replacementKeyword, Timestamp createdTs, Timestamp updatedTs) {
        super(SearchKeyword.SEARCH_KEYWORD);

        set(0, id);
        set(1, searchKeyword);
        set(2, replacementKeyword);
        set(3, createdTs);
        set(4, updatedTs);
    }
}
