/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables;


import com.scratch.database.mysql.jv.Indexes;
import com.scratch.database.mysql.jv.JvB2cDev;
import com.scratch.database.mysql.jv.Keys;
import com.scratch.database.mysql.jv.tables.records.AccountRecipeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecipe extends TableImpl<AccountRecipeRecord> {

    private static final long serialVersionUID = -1018123931;

    /**
     * The reference instance of <code>jv_b2c_dev.account_recipe</code>
     */
    public static final AccountRecipe ACCOUNT_RECIPE = new AccountRecipe();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccountRecipeRecord> getRecordType() {
        return AccountRecipeRecord.class;
    }

    /**
     * The column <code>jv_b2c_dev.account_recipe.id</code>.
     */
    public final TableField<AccountRecipeRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>jv_b2c_dev.account_recipe.recipe_id</code>.
     */
    public final TableField<AccountRecipeRecord, ULong> RECIPE_ID = createField("recipe_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>jv_b2c_dev.account_recipe.account_id</code>.
     */
    public final TableField<AccountRecipeRecord, ULong> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>jv_b2c_dev.account_recipe.created_ts</code>.
     */
    public final TableField<AccountRecipeRecord, Timestamp> CREATED_TS = createField("created_ts", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>jv_b2c_dev.account_recipe</code> table reference
     */
    public AccountRecipe() {
        this(DSL.name("account_recipe"), null);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.account_recipe</code> table reference
     */
    public AccountRecipe(String alias) {
        this(DSL.name(alias), ACCOUNT_RECIPE);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.account_recipe</code> table reference
     */
    public AccountRecipe(Name alias) {
        this(alias, ACCOUNT_RECIPE);
    }

    private AccountRecipe(Name alias, Table<AccountRecipeRecord> aliased) {
        this(alias, aliased, null);
    }

    private AccountRecipe(Name alias, Table<AccountRecipeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> AccountRecipe(Table<O> child, ForeignKey<O, AccountRecipeRecord> key) {
        super(child, key, ACCOUNT_RECIPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JvB2cDev.JV_B2C_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCOUNT_RECIPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AccountRecipeRecord, ULong> getIdentity() {
        return Keys.IDENTITY_ACCOUNT_RECIPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccountRecipeRecord> getPrimaryKey() {
        return Keys.KEY_ACCOUNT_RECIPE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccountRecipeRecord>> getKeys() {
        return Arrays.<UniqueKey<AccountRecipeRecord>>asList(Keys.KEY_ACCOUNT_RECIPE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecipe as(String alias) {
        return new AccountRecipe(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccountRecipe as(Name alias) {
        return new AccountRecipe(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRecipe rename(String name) {
        return new AccountRecipe(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AccountRecipe rename(Name name) {
        return new AccountRecipe(name, null);
    }
}
