/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables;


import com.scratch.database.mysql.jv.Indexes;
import com.scratch.database.mysql.jv.JvB2cDev;
import com.scratch.database.mysql.jv.Keys;
import com.scratch.database.mysql.jv.tables.records.CacheRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cache extends TableImpl<CacheRecord> {

    private static final long serialVersionUID = 1060567878;

    /**
     * The reference instance of <code>jv_b2c_dev.cache</code>
     */
    public static final Cache CACHE = new Cache();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CacheRecord> getRecordType() {
        return CacheRecord.class;
    }

    /**
     * The column <code>jv_b2c_dev.cache.id</code>.
     */
    public final TableField<CacheRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jv_b2c_dev.cache.hash_key</code>.
     */
    public final TableField<CacheRecord, String> HASH_KEY = createField("hash_key", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>jv_b2c_dev.cache.json_value</code>.
     */
    public final TableField<CacheRecord, String> JSON_VALUE = createField("json_value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>jv_b2c_dev.cache.created_ts</code>.
     */
    public final TableField<CacheRecord, Timestamp> CREATED_TS = createField("created_ts", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>jv_b2c_dev.cache.updated_ts</code>.
     */
    public final TableField<CacheRecord, Timestamp> UPDATED_TS = createField("updated_ts", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>jv_b2c_dev.cache</code> table reference
     */
    public Cache() {
        this(DSL.name("cache"), null);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.cache</code> table reference
     */
    public Cache(String alias) {
        this(DSL.name(alias), CACHE);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.cache</code> table reference
     */
    public Cache(Name alias) {
        this(alias, CACHE);
    }

    private Cache(Name alias, Table<CacheRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cache(Name alias, Table<CacheRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Cache(Table<O> child, ForeignKey<O, CacheRecord> key) {
        super(child, key, CACHE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JvB2cDev.JV_B2C_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CACHE_CACHE_KEY_UINDEX, Indexes.CACHE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CacheRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CACHE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CacheRecord> getPrimaryKey() {
        return Keys.KEY_CACHE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CacheRecord>> getKeys() {
        return Arrays.<UniqueKey<CacheRecord>>asList(Keys.KEY_CACHE_PRIMARY, Keys.KEY_CACHE_CACHE_KEY_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cache as(String alias) {
        return new Cache(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cache as(Name alias) {
        return new Cache(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Cache rename(String name) {
        return new Cache(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Cache rename(Name name) {
        return new Cache(name, null);
    }
}
