/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables;


import com.scratch.database.mysql.jv.Indexes;
import com.scratch.database.mysql.jv.JvB2cDev;
import com.scratch.database.mysql.jv.Keys;
import com.scratch.database.mysql.jv.tables.records.ProductPriceRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductPrice extends TableImpl<ProductPriceRecord> {

    private static final long serialVersionUID = -1755618995;

    /**
     * The reference instance of <code>jv_b2c_dev.product_price</code>
     */
    public static final ProductPrice PRODUCT_PRICE = new ProductPrice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductPriceRecord> getRecordType() {
        return ProductPriceRecord.class;
    }

    /**
     * The column <code>jv_b2c_dev.product_price.id</code>.
     */
    public final TableField<ProductPriceRecord, ULong> ID = createField("id", org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>jv_b2c_dev.product_price.item_number</code>.
     */
    public final TableField<ProductPriceRecord, String> ITEM_NUMBER = createField("item_number", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>jv_b2c_dev.product_price.price</code>.
     */
    public final TableField<ProductPriceRecord, BigDecimal> PRICE = createField("price", org.jooq.impl.SQLDataType.DECIMAL(10, 2), this, "");

    /**
     * Create a <code>jv_b2c_dev.product_price</code> table reference
     */
    public ProductPrice() {
        this(DSL.name("product_price"), null);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.product_price</code> table reference
     */
    public ProductPrice(String alias) {
        this(DSL.name(alias), PRODUCT_PRICE);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.product_price</code> table reference
     */
    public ProductPrice(Name alias) {
        this(alias, PRODUCT_PRICE);
    }

    private ProductPrice(Name alias, Table<ProductPriceRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductPrice(Name alias, Table<ProductPriceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ProductPrice(Table<O> child, ForeignKey<O, ProductPriceRecord> key) {
        super(child, key, PRODUCT_PRICE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JvB2cDev.JV_B2C_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUCT_PRICE_PRIMARY, Indexes.PRODUCT_PRICE_PRODUCT_PRICE_ITEM_NUMBER_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProductPriceRecord, ULong> getIdentity() {
        return Keys.IDENTITY_PRODUCT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductPriceRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_PRICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductPriceRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductPriceRecord>>asList(Keys.KEY_PRODUCT_PRICE_PRIMARY, Keys.KEY_PRODUCT_PRICE_PRODUCT_PRICE_ITEM_NUMBER_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPrice as(String alias) {
        return new ProductPrice(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPrice as(Name alias) {
        return new ProductPrice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductPrice rename(String name) {
        return new ProductPrice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductPrice rename(Name name) {
        return new ProductPrice(name, null);
    }
}
