/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables;


import com.scratch.database.mysql.jv.Indexes;
import com.scratch.database.mysql.jv.JvB2cDev;
import com.scratch.database.mysql.jv.Keys;
import com.scratch.database.mysql.jv.enums.S2kOrderStatusCodeCode;
import com.scratch.database.mysql.jv.tables.records.S2kOrderStatusCodeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class S2kOrderStatusCode extends TableImpl<S2kOrderStatusCodeRecord> {

    private static final long serialVersionUID = -1145510730;

    /**
     * The reference instance of <code>jv_b2c_dev.s2k_order_status_code</code>
     */
    public static final S2kOrderStatusCode S2K_ORDER_STATUS_CODE = new S2kOrderStatusCode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<S2kOrderStatusCodeRecord> getRecordType() {
        return S2kOrderStatusCodeRecord.class;
    }

    /**
     * The column <code>jv_b2c_dev.s2k_order_status_code.id</code>.
     */
    public final TableField<S2kOrderStatusCodeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>jv_b2c_dev.s2k_order_status_code.code</code>.
     */
    public final TableField<S2kOrderStatusCodeRecord, S2kOrderStatusCodeCode> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(2).nullable(false).asEnumDataType(com.scratch.database.mysql.jv.enums.S2kOrderStatusCodeCode.class), this, "");

    /**
     * The column <code>jv_b2c_dev.s2k_order_status_code.name</code>.
     */
    public final TableField<S2kOrderStatusCodeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(40).nullable(false), this, "");

    /**
     * Create a <code>jv_b2c_dev.s2k_order_status_code</code> table reference
     */
    public S2kOrderStatusCode() {
        this(DSL.name("s2k_order_status_code"), null);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.s2k_order_status_code</code> table reference
     */
    public S2kOrderStatusCode(String alias) {
        this(DSL.name(alias), S2K_ORDER_STATUS_CODE);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.s2k_order_status_code</code> table reference
     */
    public S2kOrderStatusCode(Name alias) {
        this(alias, S2K_ORDER_STATUS_CODE);
    }

    private S2kOrderStatusCode(Name alias, Table<S2kOrderStatusCodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private S2kOrderStatusCode(Name alias, Table<S2kOrderStatusCodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> S2kOrderStatusCode(Table<O> child, ForeignKey<O, S2kOrderStatusCodeRecord> key) {
        super(child, key, S2K_ORDER_STATUS_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JvB2cDev.JV_B2C_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.S2K_ORDER_STATUS_CODE_PRIMARY, Indexes.S2K_ORDER_STATUS_CODE_S2K_ORDER_STATUS_CODE_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<S2kOrderStatusCodeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_S2K_ORDER_STATUS_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<S2kOrderStatusCodeRecord> getPrimaryKey() {
        return Keys.KEY_S2K_ORDER_STATUS_CODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<S2kOrderStatusCodeRecord>> getKeys() {
        return Arrays.<UniqueKey<S2kOrderStatusCodeRecord>>asList(Keys.KEY_S2K_ORDER_STATUS_CODE_PRIMARY, Keys.KEY_S2K_ORDER_STATUS_CODE_S2K_ORDER_STATUS_CODE_ID_UINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCode as(String alias) {
        return new S2kOrderStatusCode(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public S2kOrderStatusCode as(Name alias) {
        return new S2kOrderStatusCode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public S2kOrderStatusCode rename(String name) {
        return new S2kOrderStatusCode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public S2kOrderStatusCode rename(Name name) {
        return new S2kOrderStatusCode(name, null);
    }
}
