/*
 * This file is generated by jOOQ.
 */
package com.scratch.database.mysql.jv.tables;


import com.scratch.database.mysql.jv.Indexes;
import com.scratch.database.mysql.jv.JvB2cDev;
import com.scratch.database.mysql.jv.Keys;
import com.scratch.database.mysql.jv.tables.records.UomRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Uom extends TableImpl<UomRecord> {

    private static final long serialVersionUID = 548904197;

    /**
     * The reference instance of <code>jv_b2c_dev.uom</code>
     */
    public static final Uom UOM = new Uom();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UomRecord> getRecordType() {
        return UomRecord.class;
    }

    /**
     * The column <code>jv_b2c_dev.uom.id</code>.
     */
    public final TableField<UomRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>jv_b2c_dev.uom.name</code>.
     */
    public final TableField<UomRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>jv_b2c_dev.uom.created_ts</code>.
     */
    public final TableField<UomRecord, Timestamp> CREATED_TS = createField("created_ts", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>jv_b2c_dev.uom</code> table reference
     */
    public Uom() {
        this(DSL.name("uom"), null);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.uom</code> table reference
     */
    public Uom(String alias) {
        this(DSL.name(alias), UOM);
    }

    /**
     * Create an aliased <code>jv_b2c_dev.uom</code> table reference
     */
    public Uom(Name alias) {
        this(alias, UOM);
    }

    private Uom(Name alias, Table<UomRecord> aliased) {
        this(alias, aliased, null);
    }

    private Uom(Name alias, Table<UomRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Uom(Table<O> child, ForeignKey<O, UomRecord> key) {
        super(child, key, UOM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return JvB2cDev.JV_B2C_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.UOM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UomRecord> getPrimaryKey() {
        return Keys.KEY_UOM_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UomRecord>> getKeys() {
        return Arrays.<UniqueKey<UomRecord>>asList(Keys.KEY_UOM_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uom as(String alias) {
        return new Uom(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Uom as(Name alias) {
        return new Uom(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Uom rename(String name) {
        return new Uom(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Uom rename(Name name) {
        return new Uom(name, null);
    }
}
